import { Route, Routes } from "react-router-dom"
import Home from "../Pages/Home"
import About from "../Pages/About";
import Projects from "../Pages/Projects";
import App from "../Projects/React-corculation/Calculator";
import Films from "../Projects/countries route/src/App/App";
import Todo from "../Projects/todo-app/src/components/App";
import GithubSearch from '../Projects/github search/src/App'
import Yemak from "../Projects/yemak/src/App";
import Skills from "../Pages/Skills";
import Contact from "../Pages/Contact";






export default function Router({introTexts, language, mode, texts, photo}) {
    return (
      <Routes>
        <Route
          path="/home"
          element={
            <Home
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/skills"
          element={
            <Skills
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/навыки"
          element={
            <Skills
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/contact"
          element={
            <Contact
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/"
          element={
            <Home
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/главная"
          element={
            <Home
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/bosh sahifa"
          element={
            <Home
              introTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/about"
          element={
            <About
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/haqida"
          element={
            <About
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/обо мне"
          element={
            <About
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/projects"
          element={
            <Projects
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/loyihalar"
          element={
            <Projects
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/проекты"
          element={
            <Projects
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="projects/carculation"
          element={
            <App
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="projects/to-do"
          element={
            <Todo
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="projects/yemak/*"
          element={
            <Yemak
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="projects/github"
          element={
            <GithubSearch
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
        <Route
          path="/projects/films/*"
          element={
            <Films
              aboutTexts={introTexts}
              language={language}
              mode={mode}
              texts={texts}
              photo={photo}
            />
          }
        />
      </Routes>
    );
}